############################################################
# Global variables
profile: "/assets/img/20181205_211335_971.jpg"
favicon: "/assets/img/favicon.ico"
############################################################
############################################################
# gems
# jekyll-seo-tag
title: "Jehee Cheon"
description: "The place where I post about programming."
author: "Jehee Cheon"
logo: "/assets/img/logo.jpg"
social:
  name: Jehee Cheon
  links:
    - https://twitter.com/JeheeCheon
    - https://www.facebook.com/profile.php?id=100009511965571
    - https://www.linkedin.com/in/jehee-cheon-93a3081b0/
    - https://github.com/jeheecheon
    - https://www.instagram.com/jeheecheon/

# Auto image
image: "/assets/img/business-2717063_1920.jpg"

# Admin
jekyll_admin:
  hidden_links:
    - pages
    - configuration

# Paginate-v2
pagination:
  enabled: true
  per_page: 3
  permalink: "/page-:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  collection: "posts"
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: "index"

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "autopage_category.html"
    title: "Posts in category :cat"
    dir: categories
    permalink: "/categories/:cat"
    slugify:
      mode: "default" # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false # Whether to replace all uppercase letters with their lowercase counterparts
  tags:
    enabled: true
    layouts:
      - "autopage_tag.html"
    title: "Posts tagged with :tag" # :tag is replaced by the tag name
    dir: tags
    permalink: "/tags/:tag"
    slugify:
      mode: "default" # :tag is slugified.
      case: false
  collections:
    enabled: false

# jekyll-autolink_email
autolink_email:
  link_attr: class='email-link' # attributes to add to the link
  skip_tags: ['div']            # tags to skip
############################################################
############################################################
# source:
destination: _site
# collections_dir     : _collections
data_dir: _data
includes_dir: _includes
layouts_dir: _layouts
sass:
  sass_dir: _sass
############################################################
# Outputting
encoding            : "utf-8"
url: https://jeheecheon.github.io
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
############################################################
# Filtering Content
# show_drafts: null
# limit_posts: 0
# future: false
# unpublished: false
############################################################
# Handling Reading
safe: false
include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false
