############################################################
# Global variables
title: "Jehee Cheon"
blog:
  author: "Jehee Cheon"
  profile: "/assets/img/20181205_211335_971.jpg"
  logo: "/assets/img/pooh.jpg"
  description: "Game Developer..."
favicon: "/assets/img/favicon.ico"
############################################################
############################################################
# gems
# Auto image
image: "/assets/img/business-2717063_1920.jpg"

# Admin
jekyll_admin:
  hidden_links:
    - pages
    - configuration

# Paginate-v2
pagination:
  enabled: true
  per_page: 3
  permalink: "/page-:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  collection: "posts"
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: "index"

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - "autopage_category.html"
    title: "Posts in category :cat"
    dir: categories
    permalink: "/categories/:cat"
    slugify:
      mode: "default" # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false # Whether to replace all uppercase letters with their lowercase counterparts
  tags:
    enabled: true
    layouts:
      - "autopage_tag.html"
    title: "Posts tagged with :tag" # :tag is replaced by the tag name
    dir: tags
    permalink: "/tags/:tag"
    slugify:
      mode: "default" # :tag is slugified.
      case: false
  collections:
    enabled: false
############################################################
############################################################
# source:
destination: _site
# collections_dir     : _collections
data_dir: _data
includes_dir: _includes
layouts_dir: _layouts
sass:
  sass_dir: _sass
############################################################
# Outputting
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
############################################################
# Filtering Content
# show_drafts: null
# limit_posts: 0
# future: false
# unpublished: false
############################################################
# Handling Reading
safe: false
include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false
